config/routes.rb
Rails.application.routes.draw do
  # get 'books' => 'books#index'
  # get 'books/:id' => 'books#show'
  # post 'books' => 'books#create'
  # get 'books/:id/edit' => 'books#edit'
  # patch 'books/:id' => 'books#update'
  # delete 'books/destroy/:id' => 'books#destroy'
  get '/' => 'homes#index', as: :root
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end
  def create
    @book = Book.new(list_params)
    if @book.save
      redirect_to "/books/#{@book.id}", notice:"Book was successfully created."
    else 
      @books = Book.all
      render :index
    end
  end
  def show
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(list_params)
      redirect_to "/books/#{@book.id}" ,notice:"Book was successfully updated."
    else
      render :edit
    end
  end
  private
  def list_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<div id = "error_explanation">
    <h2><% if @book.errors.count >= 2%>
            <%= @book.errors.count %> errors prohibited this book from begin saved:
        <% else %>
            <%= @book.errors.count %> error prohibited this book from begin saved:
        <% end %>
    </h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
</div>
<% end %>
<%= form_with model: @book,url: book_path(@book.id) , method: :patch do |f| %>
<div class = "field">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class = "field">
<%= f.label :body %>
<%= f.text_area :body %>
</div>
<div class = "actions">
  <%= f.submit 'Update Book' %>
</div>
<% end %>
<%= link_to "Show" , book_path(@book.id) ,method: :get %> | 
<%= link_to "Back" , "/books" %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan = "3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |element|  %>
    <tr>
    <td><%= element.title %></td>
    <td><%= element.body %></td>
    <td><%= link_to "Show", book_path(element.id), method: :get %></td>
    <td><%= link_to "Edit",  edit_book_path(element.id) %></td>
    <td><%= link_to "Destroy", book_path(element.id), method: :delete,"data-confirm" => "Are you sure？" %></td>
    <% end %>
    </tr>
  </tbody>
</table>
<h2>New Book</h2>
<% if @book.errors.any? %>
  <div id = "error_explanation">
  <h2>
      <%if @book.errors.count>=2 %>
        <%= @book.errors.count %> errors prohibited this book from begin saved:
      <% else %>
        <%= @book.errors.count %> error prohibited this book from begin saved:
      <% end %>
  </h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>  
<%= form_with model: @book, url: books_path , method: :post do |f| %>
<div class = "field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class = "field">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p id = "notice"><%= notice %></p>
<p>
<strong>Title:</strong>
<%= @book.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %> | 
<%= link_to "Back", "/books" %>

app/views/homes/index.html.erb
<h1>ようこそ Bookers へ！</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することが出来ます
</p>
<p>
  <a  href = "/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>